name: hadoop-hive

services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    platform: linux/amd64
    command: ["hdfs", "namenode"]
    environment:
      # La imagen formatea el NameNode la primera vez si esta carpeta no existe.
      ENSURE_NAMENODE_DIR: /data/dfs/name
    ports:
      - "9870:9870"     # interfaz web del NameNode
    volumes:
      - namenode_data:/data
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./data:/archivos          # los datasets de tu laptop, visibles dentro del contenedor
      - ./scripts:/scripts

  datanode1:
    image: apache/hadoop:3.4.1
    container_name: datanode1
    hostname: datanode1
    platform: linux/amd64
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    ports:
      - "9864:9864"     # interfaz web del DataNode
    volumes:
      - datanode1_data:/data
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml


  hiveserver2:
    image: apache/hive:4.0.0
    container_name: hiveserver2
    hostname: hiveserver2
    platform: linux/amd64
    depends_on:
      - namenode
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./config/hadoop/core-site.xml:/hive_custom_conf/core-site.xml
      - ./config/hadoop/hdfs-site.xml:/hive_custom_conf/hdfs-site.xml
      - ./config/hive/hive-site.xml:/hive_custom_conf/hive-site.xml


volumes:
  namenode_data:
  datanode1_data: